# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo Merge
        run: echo "merge"
