# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
  pull_request_target:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo Base
        run: echo "base"
